#!/bin/bash

# List of services to monitor
SERVICES=("ams.service" "another.service" "example.service")

while true; do
    clear
    for SERVICE in "${SERVICES[@]}"; do
        STATUS=$(systemctl is-active $SERVICE)
        
        if [ "$STATUS" = "active" ]; then
            echo -e "$SERVICE: \e[32m●\e[0m"  # Blinking green light
        else
            echo -e "$SERVICE: \e[31m●\e[0m"  # Blinking red light
        fi
    done
    sleep 1
done
